jobs: 100000000

# Configure for Snakemake >= 8.0
executor: "cluster-generic"
cluster-generic-submit-cmd: "sbatch -A {resources.account} -p {resources.partition} -J {rule}.job --qos {resources.partition} --cpus-per-task={threads} -e logs/cluster/{rule}_%A.err --output=/dev/null" 
software-deployment-method: "conda"
default-resources: [account='mdbf', partition='mid_mdbf']


printshellcmds: True
keep-going: True
rerun-incomplete: True
rerun-triggers: "mtime"
